import { FilterBar } from "@/components/admin/FilterBar";
import { IconButton } from "@/components/admin/IconButton";
import { LayoutToggle } from "@/components/admin/LayoutToggle";
import { MerchantLogo } from "@/components/admin/MerchantLogo";
import { PageHeader } from "@/components/admin/PageHeader";
import { StatusBadge } from "@/components/admin/StatusBadge";
import { Button } from "@/components/ui/button";
import { Tooltip as UiTooltip, TooltipContent as UiTooltipContent, TooltipProvider, TooltipTrigger as UiTooltipTrigger } from "@/components/ui/tooltip";

import { downloadCsv } from "@/lib/admin-utils";
import { cn } from "@/lib/utils";
import type { Category, LayoutMode, Merchant, Status } from "@/types/admin";
import { ChevronDown, ChevronLeft, ChevronRight, Download, ExternalLink, Pencil, Plus, Tag } from "lucide-react";
import { useMemo, useState } from "react";

export function Merchants({ rows: merchantRows, onEdit }: { rows: readonly (Merchant)[]; onEdit: (merchant: Merchant) => void }) {
  const [query, setQuery] = useState(""); const [statuses, setStatuses] = useState<Status[]>([]); const [sortAsc, setSortAsc] = useState(true); const [layout, setLayout] = useState<LayoutMode>("list");
  const rows = useMemo(() => merchantRows.filter((m) => (!query || `${m[0]} ${m[2]}`.toLowerCase().includes(query.toLowerCase())) && (!statuses.length || statuses.includes(m[4] as Status))).sort((a, b) => sortAsc ? a[0].localeCompare(b[0]) : b[0].localeCompare(a[0])), [query, statuses, sortAsc, merchantRows]);
  return <><PageHeader title="Merchants" description="Manage merchant availability, categorisation, and channel details." actions={<><LayoutToggle value={layout} onChange={setLayout} /><Button><Plus />Add new</Button></>} /><FilterBar query={query} setQuery={setQuery} statuses={statuses} setStatuses={setStatuses} showChannel actions={<Button variant="outline" size="sm" className="shrink-0" onClick={() => downloadCsv(rows.map((m) => ({ Name: m[0], Channel: m[1], Category: m[2], Offers: m[5], Commission: m[6], Cities: (m[7] as readonly string[]).join(" | "), Order: m[3], Status: m[4] })), "offerpe-merchants.csv")}><Download className="mr-1 h-3.5 w-3.5" />Export CSV</Button>} />{layout === "grid" ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map((m) => <article key={m[0]} className="flex min-h-88 flex-col overflow-hidden rounded-lg border border-border bg-card shadow-card">
      <div className="flex h-40 items-center justify-center border-b border-border bg-muted/40"><MerchantLogo name={m[0]} /></div>
      <div className="flex flex-1 flex-col gap-3 p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="font-heading text-base font-bold">{m[0]}</div><div className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><span className={cn("h-2 w-2 rounded-full", m[1] === "Online" ? "bg-success" : "bg-info")} />{m[1]} · {m[2]}</div></div><StatusBadge status={m[4] as Status} /></div>
      <div className="flex flex-wrap items-center gap-2 text-xs"><span className="inline-flex items-center gap-1 rounded-full bg-accent px-2 py-0.5 font-semibold text-accent-foreground"><Tag className="h-3 w-3" />{m[5]} active offers</span><span className="rounded-full border border-border bg-muted px-2 py-0.5 font-semibold">{m[6]} commission</span></div>
      <div className="flex flex-wrap gap-1">{(m[7] as readonly string[]).slice(0, 4).map((city) => <span key={city} className="rounded-full border border-border bg-muted px-2 py-0.5 text-xs font-medium">{city}</span>)}{m[7].length > 4 && <span className="rounded-full border border-border bg-accent px-2 py-0.5 text-xs font-semibold text-primary">+{m[7].length - 4}</span>}</div>
      <div className="mt-auto flex items-center justify-between pt-1 text-xs text-muted-foreground"><span>Order {m[3]}</span><Button variant="outline" size="sm" className="h-8" onClick={() => onEdit(m)}><Pencil className="h-3.5 w-3.5" />Edit</Button></div>
      </div>
    </article>)}{rows.length === 0 && <div className="rounded-lg border border-dashed border-border bg-card p-10 text-center text-sm text-muted-foreground sm:col-span-2 xl:col-span-3">No merchants match these filters.</div>}</div> : <div className="overflow-hidden rounded-lg border border-border bg-card shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-310 text-left text-sm"><thead className="bg-muted/70 text-[11px] uppercase text-muted-foreground"><tr><th className="sticky left-0 z-10 bg-muted px-4 py-2 shadow-sticky-left"><Button variant="ghost" size="sm" className="-ml-3 h-7 text-[11px] uppercase" onClick={() => setSortAsc(!sortAsc)}>Name <ChevronDown className={cn("transition-transform", !sortAsc && "rotate-180")} /></Button></th><th>Channel</th><th>Category</th><th>Offers</th><th>Commission</th><th>Cities</th><th>Order</th><th>Status</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{rows.map((m) => <tr key={m[0]} className="group border-t border-border hover:bg-muted/50"><td className="sticky left-0 z-10 bg-card px-4 py-2 font-semibold shadow-sticky-left group-hover:bg-muted">{m[0]}</td><td><span className="inline-flex items-center gap-1.5 font-medium"><span className={cn("h-2 w-2 rounded-full", m[1] === "Online" ? "bg-success" : "bg-info")} />{m[1]}</span></td><td>{m[2]}</td><td><span className="inline-flex items-center gap-1 rounded-full bg-accent px-2 py-0.5 text-xs font-semibold text-accent-foreground"><Tag className="h-3 w-3" />{m[5]} active</span></td><td className="whitespace-nowrap font-semibold">{m[6]}</td><td><div className="flex min-w-64 items-center gap-1">{m[7].slice(0, 3).map((city) => <span key={city} className="rounded-full border border-border bg-muted px-2 py-0.5 text-xs font-medium">{city}</span>)}{m[7].length > 3 && <TooltipProvider><UiTooltip><UiTooltipTrigger asChild><button type="button" className="rounded-full border border-border bg-accent px-2 py-0.5 text-xs font-semibold text-primary">+{m[7].length - 3} more</button></UiTooltipTrigger><UiTooltipContent>{m[7].join(", ")}</UiTooltipContent></UiTooltip></TooltipProvider>}</div></td><td>{m[3]}</td><td><StatusBadge status={m[4] as Status} /></td><td className="pr-3 text-right"><IconButton className="h-7 w-7" label={`Edit ${m[0]}`} onClick={() => onEdit(m)}><Pencil className="h-3.5 w-3.5" /></IconButton><IconButton className="h-7 w-7" label={`Open ${m[0]}`} onClick={() => onEdit(m)}><ExternalLink className="h-3.5 w-3.5" /></IconButton></td></tr>)}</tbody></table></div></div>}<div className="mt-4 flex items-center justify-between text-sm text-muted-foreground"><span>Showing {rows.length} of {merchantRows.length} merchants</span><div className="flex gap-1"><Button variant="outline" size="icon" disabled><ChevronLeft /></Button><Button variant="outline" size="icon"><ChevronRight /></Button></div></div></>;
}
